export const featuredCollections = [
  "Star Wars",
  "Harry Potter",
  "The Lord of the Rings Collection",
  "Pirates of the Caribbean",
  "Jurassic Park",
  "The Godfather",
  "Transformers",
  "Indiana Jones",
  "Fast & Furious",
  "Mission: Impossible",
  "The Matrix",
  "James Bond",
  "The Hunger Games",
  "Shrek",
  "Top Gun Collection",
  "The Hobbit",
  "Taken",
  "The Terminator",
  "The Dark Knight",
  "Guardians of the Galaxy",
  "The Avengers",
  "Ghostbusters",
  "Finding Nemo",
  "Planet of the Apes",
  "Toy Story",
  "Iron Man",
  "The Incredibles",
  "Captain America",
  "The Amazing Spider-Man",
  "Kung Fu Panda",
  "Spider-Man Collection",
  "Die Hard Collection",
];